### init admin
GET localhost:808/init/admin

### init login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}
### init login
POST http://localhost:8080/auth/moder
Content-Type: application/json

{
  "email": "azim@gmail.com",
  "password": "1111"
}

### init login
POST http://localhost:8080/auth/moder
Content-Type: application/json

{
  "email": "sunnat@gmail.com",
  "password": "1111"
}