

### init login
POST localhost:8080/article/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng

{
  "articleName": "articleName",
  "nameUz": "articleNameUz",
  "nameEn": "articleNameEn",
  "nameRu": "articleNameRu",
  "visible": true
}


### update Article
PUT localhost:8080/article/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng


{
  "visible": false,
  "articleName": "Xabar24",
  "nameUz": "sportUz",
  "nameEn": "sportEn",
  "nameRu": "sportRu"
}


### getList Article
GET localhost:8080/article/language?language=UZ


### getList Article
DELETE localhost:8080/article/1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng

### getList Article
GET localhost:8080/article/Pagination?size=1&page=1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng
