

### init login
POST localhost:8080/article/create
Content-Type: application/json

{
  "articleName": "Sport",
  "nameUz": "sportUz",
  "nameEn": "sportEn",
  "nameRu": "sportRu",
  "visible": true
}


### update Article
PUT localhost:8080/article/1
Content-Type: application/json

{
  "visible": false,
  "articleName": "Xabar24",
  "nameUz": "sportUz",
  "nameEn": "sportEn",
  "nameRu": "sportRu"
}


### getList Article
GET localhost:8080/article/language?language=uz


### getList Article
DELETE localhost:8080/article/1
