### create article
POST localhost:8080/article/moder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDU2MjcsImVtYWlsIjoiYXppbUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NT0RFUkFUT1IiLCJleHAiOjE3MDgwOTIwMjcsImlzcyI6Ikt1blV6VGVzdCJ9.-ftl6YtksvFiQS5F1wlkeJIQJk_8bYb4idifX2hSMct0qeOmq7fgaMo7HE0qzRH3f8A6Scv6ZifEsVOBwsYFgg

{
  "title": "fan",
  "description": "Fan-Texnika",
  "content": "Ilim - fan",
  "imagesId": "9ed417ba-1284-48df-82d9-0e86d292697b",
  "regionId":8,
  "cagtegoryId": 5,
  "types": [1,2]
}

### update article
PUT localhost:8080/article/moder/d157b3ab-a240-41b5-8963-81476d576c91
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODQyNTQsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3NDcwNjU0LCJpc3MiOiJLdW5VelRlc3QifQ.lT7o7qmAsKiWmAvEBLP9MGB4bFgQPjY2NJ22x0vxzb9oJVtK3YlmuCF29Wy34wVLBRdB3ccbfWPDSK9MtvCMEA

{
  "title": "article1",
  "description": "article2",
  "content": "article1",
  "imagesId": "d157b3ab-a240-41b5-8963-81476d576c91",
  "regionId": 2,
  "categoryId": 3,
  "types": [2,4]
}


### updateVisible (Visble=false)
PUT localhost:8080/article/moder/updateVisible/10fa932c-d9a2-4ab4-8b85-97d96c92
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODQyNTQsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3NDcwNjU0LCJpc3MiOiJLdW5VelRlc3QifQ.lT7o7qmAsKiWmAvEBLP9MGB4bFgQPjY2NJ22x0vxzb9oJVtK3YlmuCF29Wy34wVLBRdB3ccbfWPDSK9MtvCMEA




### updateStatus (Status =PUBLISHED)
PUT localhost:8080/article/pub/updateStatus/669c6f31-3f97-4625-88ef-d6c077d093e6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODc2MjMsImlkIjoyLCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNzA3NDc0MDIzLCJpc3MiOiJLdW5VelRlc3QifQ.QNhKP-Rq1Sfn6bgvrsR9SOESZhowOhcp-OpLYc11t7awSh9DRYeaBusX3fOPYdDzjYBGul3jFMBvzmrzNycIyQ

### typesID(GET)
GET localhost:8080/article/ArticleByTypes?id=4&size=0

### ArticleSwitchId(GET)
GET localhost:8080/article/ArticleSwitchId/4

### Lan(GET)
GET localhost:8080/article/getLanguage/bceba2df-8b74-4cdf-a3c9-07e0d282e22f?lan=UZ

### ArticleTypesIDGivenArticleID(GET)
GET localhost:8080/article/ArticleByTypesAndExceptArticleId/4?articleID=12e15f36-8b1f-4f2e-a55f-d907662ea195

### ArticleTypesIDGivenArticleID(GET)
###150689bf-adfb-41b2-bff1-d948119976e1
###12e15f36-8b1f-4f2e-a55f-d907662ea195
###669c6f31-3f97-4625-88ef-d6c077d093e6
GET localhost:8080/article/GetReaderArticle


### ArticleTypesIDandRegionID(GET)
GET localhost:8080/article/ArticleByTypesIDAndByRegionID/2?regionID=2

### regionIdAndLan(GET)
GET localhost:8080/article/regionIdAndLan/7?lan=EN&size=1&page=1

### categoryIdAndLan(GET)
GET localhost:8080/article/CategoryIDAndLan/2?lan=UZ


### CategoryIdAndLan(GET)
GET localhost:8080/article/categoryIdAndLan/1?lan=UZ&size=2&page=2

### viewCountPlus(Put)
PUT localhost:8080/article/viewCount/4cd82f91-c40f-44a9-9f59-03a677df788

### ShareViewCountPlus(Put)
PUT localhost:8080/article/ShareViewCount/12e15f36-8b1f-4f2e-a55f-d907662ea195

### Filter(Put)
GET localhost:8080/article/pub/filter?page=1&size=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc1NzA5NDcsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3NjU3MzQ3LCJpc3MiOiJLdW5VelRlc3QifQ.05YeAQhLbBgg88sNdPsEivAOdMMAVt9m71UvYP7ehdE2oe7Ktjug_4cyrbNXI7_ey8YxmC2awh3Q1pt5h9qSFA

{
  "title": "article"
}


### createArticleTagName(Put)
POST localhost:8080/article/tagName/adm?articleID=73af69ec-01ff-4947-8b9d-0dada8f9b0d9&tagNameID=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDU5OTksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDkyMzk5LCJpc3MiOiJLdW5VelRlc3QifQ.9o6HvZeYbMswRsOx-QgjJuhy1oz8WZ-ok6EzuS-JV9uAF-uLFJA_sazVv1IZvxjpWrwjqlnV7T5qB_sI0oLsZA

