### Create
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.jpg"

< C:\Coduz\1.jpg

### GET
GET http://localhost:8080/attach/open/test.jpg

### GET
GET http://localhost:8080/attach/open_general/sample-3s.mp3

### GET
GET http://localhost:8080/attach/download/6fa148b8-b77e-40be-9326-610f03d0d0c3.jpg


### GET(pagination)
GET http://localhost:8080/attach/adm/pagination?size=1&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODQ3MDMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0NzExMDMsImlzcyI6Ikt1blV6VGVzdCJ9.55ddIYz7DG4N-Fc1LjcUivLoiMPU10WdqZBmJpuxXYJ7OxW3Oo15TGN3e7QJLzkfDf6rYf-8wPMeLqv6Zxt1HQ



### Delete(id)
DELETE localhost:8080/attach/adm/delete/9ee11cfd-bfba-4f96-a195-02a79502cda4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODQ3MDMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0NzExMDMsImlzcyI6Ikt1blV6VGVzdCJ9.55ddIYz7DG4N-Fc1LjcUivLoiMPU10WdqZBmJpuxXYJ7OxW3Oo15TGN3e7QJLzkfDf6rYf-8wPMeLqv6Zxt1HQ


### Create
POST http://localhost:8080/attach/adm/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODQ3MDMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0NzExMDMsImlzcyI6Ikt1blV6VGVzdCJ9.55ddIYz7DG4N-Fc1LjcUivLoiMPU10WdqZBmJpuxXYJ7OxW3Oo15TGN3e7QJLzkfDf6rYf-8wPMeLqv6Zxt1HQ

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3.jpg"

< C:\Coduz\3.jpg






