### Create
POST http://localhost:8080/attach/upload1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"

< C:\Users\Laptop\Downloads\Telegram Desktop\test.jpg

### GET
GET http://localhost:8080/attach/open/test.jpg

### GET
GET http://localhost:8080/attach/open_general/sample-3s.mp3

### GET
GET http://localhost:8080/attach/download/6fa148b8-b77e-40be-9326-610f03d0d0c3.jpg


### GET(pagination)
GET http://localhost:8080/attach/adm/pagination?size=1&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczMDE3NTksImlkIjozMiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzg4MTU5LCJpc3MiOiJLdW5VelRlc3QifQ.jKXoId7DF-EdBORnA7DGEejvKeR4c56KnlFNFQA6DfzhlXOu7ZfitIBB10AuJIpU8g9kSVhuKrORJ_6YhtfJLw



### Delete(id)
DELETE localhost:8080/attach/adm/delete/9ee11cfd-bfba-4f96-a195-02a79502cda4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczMDY4NDQsImlkIjozMSwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzM5MzI0NCwiaXNzIjoiS3VuVXpUZXN0In0.g6lKtUg_wWsBNyKscdBWDRELuAMHSIwOch-yCnF3A1ooCaJTBNcrhkJqo1WBarfpDFdJglHxm_XsQR-FhKf9KA