### Create
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"

< C:\Users\Laptop\Downloads\Telegram Desktop\test.jpg

### GET
GET http://localhost:8080/attach/open/test.jpg

### GET
GET http://localhost:8080/attach/open_general/sample-3s.mp3

### GET
GET http://localhost:8080/attach/download/6fa148b8-b77e-40be-9326-610f03d0d0c3.jpg


### GET(pagination)
GET http://localhost:8080/attach/adm/pagination?size=1&page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ



### Delete(id)
DELETE localhost:8080/attach/adm/delete/9ee11cfd-bfba-4f96-a195-02a79502cda4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ


### Create
POST http://localhost:8080/attach/adm/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDU5OTksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDkyMzk5LCJpc3MiOiJLdW5VelRlc3QifQ.9o6HvZeYbMswRsOx-QgjJuhy1oz8WZ-ok6EzuS-JV9uAF-uLFJA_sazVv1IZvxjpWrwjqlnV7T5qB_sI0oLsZA

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="efil.jpg"

< C:\Users\Laptop\Downloads\Telegram Desktop\efil.jpg






