### create Category
POST localhost:8080/category/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng


{
  "orderNumber": 2,
  "nameEn": "CategoryEn",
  "nameRu": "CategoryRu",
  "nameUz": "CategoryUz"
}


### update(id) Category
PUT localhost:8080/category/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng

{
  "orderNumber": 2,
  "nameUz": "nameUz",
  "nameRu": "nameRu",
  "nameEn": "nameEn"
}

### delete (id) Category

DELETE localhost:8080/category/1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng

### get (order by orderNumber) Category
GET localhost:8080/category/Pagination?page=1&size=1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MjYwNjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MTI0NjgsImlzcyI6Ikt1blV6VGVzdCJ9.DON9CpVvch12XEfJ0reGEHBmvJb6uOm_o5Fz3nXTH092LK80yio2cp41CW867JIg861i9cSFFokP-d3Sj5o2Ng

### getLanguage (Language) Category
GET localhost:8080/category/language?language=RU
