### create Category
POST localhost:8080/category/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ



{
  "orderNumber": 4,
  "nameEn": "XAMAS_UZ",
  "nameRu": "XAMAS_Ru",
  "nameUz": "XAMAS_Uz"
}


### update(id) Category
PUT localhost:8080/category/adm/1
Content-Type: application/json
Authorization: Baarer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

{
  "orderNumber": 2,
  "nameUz": "nameUz",
  "nameRu": "nameRu",
  "nameEn": "nameEn"
}

### delete (id) Category

DELETE localhost:8080/category/adm/1
Authorization: Baarer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

### get (order by orderNumber) Category
GET localhost:8080/category/adm/Pagination?page=1&size=1
Authorization: Baarer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

### getLanguage (Language) Category
GET localhost:8080/category/language?language=RU
