### create Profile
POST localhost:8080/profile/adm/crate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

{
  "password": "0000",
  "phone": "+998945767555",
  "name": "Azim",
  "surname": "Xoliqov",
  "status": "ACTIVE",
  "role": "ROLE_USER",
  "email": "email"

}


### update(id) Profile
PUT localhost:8080/profile/adm/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

{
  "role": "ROLE_ADMIN",
  "email": "@email",
  "status": "BLOCK",
  "name": "Karim"
}

### getList(size,page) Profile
GET localhost:8080/profile/adm/pagination?size=1&page=3
Authorization: Bearer
### filter(size,page) Profile
POST localhost:8080/profile/filter?size=1&page=2
Content-Type: application/json

{
  "role": "ROLE_ADMIN"
}

### filter(size,page) Profile
PUT localhost:8080/profile/adm/update
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5ODAwMDYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDY2NDA2LCJpc3MiOiJLdW5VelRlc3QifQ.FsK6JXREQwfaSzKOcWG59wrdqL5Jjvfni_6IflgqFh5Ez9EBpRp2LPbwB88soaqboUc6MY8fA0B2fpesIg0vPQ

{
  "name": "Kim",
  "surname": "Kimov",
  "password": "123456"
}
