### create region
POST http://localhost:8080/region/adm
Content-Type: application/json
Authorization: Baarer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MzM5NzAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MjAzNzAsImlzcyI6Ikt1blV6VGVzdCJ9.PMexRaFU-CUc2m9i0Ltl3fUxxBxacvtDHPEoqDzvvAhL0EjU8ClsgwoqKTYT_GzugXWkVDb62xslSdI87t4-Sw

{
  "visible": false,
  "orderNumber": 2,
  "nameUz": "Samarqand UZ",
  "nameRu": "Samarqand RU",
  "nameEn": "Samarqand EN"
}



### update region
PUT localhost:8080/region/adm/1
Content-Type: application/json
Authorization: Baarer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MzM5NzAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MjAzNzAsImlzcyI6Ikt1blV6VGVzdCJ9.PMexRaFU-CUc2m9i0Ltl3fUxxBxacvtDHPEoqDzvvAhL0EjU8ClsgwoqKTYT_GzugXWkVDb62xslSdI87t4-Sw

{
  "visible": true,
  "orderNumber": 3,
  "nameUz": "Shahar UZ",
  "nameRu": "Xorazm RU",
  "nameEn": "Shahar En"

}

### delete  region
DELETE localhost:8080/region/adm/5
Authorization: Baarer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MzM5NzAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MjAzNzAsImlzcyI6Ikt1blV6VGVzdCJ9.PMexRaFU-CUc2m9i0Ltl3fUxxBxacvtDHPEoqDzvvAhL0EjU8ClsgwoqKTYT_GzugXWkVDb62xslSdI87t4-Sw

### getLanguage  region
GET localhost:8080/region/adm/language?lan=RU
Authorization: Baarer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MzM5NzAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MjAzNzAsImlzcyI6Ikt1blV6VGVzdCJ9.PMexRaFU-CUc2m9i0Ltl3fUxxBxacvtDHPEoqDzvvAhL0EjU8ClsgwoqKTYT_GzugXWkVDb62xslSdI87t4-Sw
