POST http://localhost:8080/sms/create
Content-Type: application/json

{
  "name": "Kozim",
  "surName": "Nozimov",
  "password": "2233",
  "email": "No",
  "phone": "998997971636"
}
### init login

POST http://localhost:8080/sms/sms?kod=3056


