POST http://localhost:8080/sms/create
Content-Type: application/json

{
  "name": "AKBAR",
  "surName": "O`rinboyev",
  "password": "aaaa",
  "email": "tojiyevakbar@gmail.co",
  "phone": "998945767546"
}
### init login

POST http://localhost:8080/sms/sms?kod=9970


